### ISSUE TITLE
Profile.generate_uniform_voters(n,m) doesn't accept integer

### ISSUE THREAD

**Issue by seyhunsaral** [seyhunsaral/choicepy#1]
`my_profile.generate_uniform_voters(3,3)` gives the following error:

```
init__.py", line 371, in set_candidates
    self.candidates = sorted(candidate_list)
TypeError: 'int' object is not iterable
```

**Comment by annikahe** [comment]
The problem is that we need to have a list or something similar iterable as first parameter of the function generate_uniform_voters. Something like this:

my_profile.generate_uniform_voters(list("abcd"),3)

If the first parameter is an int, then the function sorted(candidate_list) won't know what to do. 

But if we want to be able to insert an int as parameter, we could first generate an default candidate_list of the given length. 
Or alternatively, we could also transfer the candidate_list generation to a completely new function.

**Comment by seyhunsaral** [comment]
of course! I though we had by default the letters, which might be a good to implement. Maybe it can check whether the input is an integer or an iterable and behave accordingly.

**Comment by annikahe** [comment]
I implemented something that uses a try and except block in the set_candidates method to do this. 
I just created a pull request for this. What do you think about this solution?

**Comment by seyhunsaral** [comment]
Super thanks. I added my comments in #2

**Comment by seyhunsaral** [comment]
Just a quick question: are you able to merge a pull request by yourself? I found out that you can only add "collaborator" to a personal repo. If not, we should find out a way.

**Comment by seyhunsaral** [comment]
there were few mismatches but the commit 337192c and 8b8de1c fixes those.
